version: 2.1
jobs:
  run-test:
    docker:
      - image: cypress/base:14.16.0
    # Steps to the job
    steps:
      - checkout
      - run:
          name: Download dependency
          environment:
            SECRET_KEY: SECRET_KEY 
          command: npm ci
      - run:
          name: Run tests
          command: npm run UI-Regression
      - store_artifacts:
          path: cypress/reports
          destination: reports
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/videos
          destination: videos
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test